### ISSUE TITLE
Group #25 , showing error in jquery.min.js file 

### ISSUE THREAD

**Issue by xtmat** [FusionIIIT/Fusion#581] opened 2022-02-01 08:03 UTC
Uncaught TypeError: $(...).tablesort is not a function
    at j (jquery.min.js:2:27244)
    at Object.fireWith [as resolveWith] (jquery.min.js:2:28057)
    at Function.ready (jquery.min.js:2:29891)
    at HTMLDocument.J (jquery.min.js:2:30257)

in 
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
/Fusion/blob/main/FusionIIIT/templates/feeds/feeds_main.html

**Comment by anurag0singh** [comment] 2022-02-01 08:15
Please attach:
1. Screenshots
2.  Endpoint address/link

**Comment by anurag0singh** [comment] 2022-02-01 08:17
When is this error coming? I mean on clicking somewhere on the page or triggering some other event?

**Comment by anurag0singh** [comment] 2022-02-01 08:21
Can you also mention the endpoint link/address?

**Comment by anurag0singh** [comment] 2022-02-01 08:47
I think the issue is being rooted in tablesort.js file. So I am closing this issue and if the issue persists even after resolving it in tablesort.js you can always reopen this issue.

**Closed as completed by anurag0singh** 2022-02-01 08:47 UTC
